### ISSUE TITLE
compilation error with custom operator== defined in namespace

### ISSUE THREAD

**Issue by zvyagin1** [doctest/doctest#610] opened 2022-02-04 11:45 UTC
I have troubles compiling the code fragment below. And everything works just fine if namespace is not used. Any hints?

```
namespace N {
class MyClass {
public:
    bool operator == (const MyClass &v) const {return false;}
};
}

std::ostream & operator << (std::ostream &os, const N::MyClass &v){
    return os << "MyClass\n";
}

TEST_CASE("eq") {
    N::MyClass obj;
    std::cout << obj << "  comparison: " << (obj==obj) << "\n";
    REQUIRE(obj==obj); // does not compile!
}
```

g++-11 (Homebrew GCC 11.2.0_3) 11.2.0
#define DOCTEST_VERSION_STR "2.4.6"

**Comment by Saalvage** [comment] 2022-02-06 02:21
I'm honestly inclined to believe this is a compiler bug introduced in GCC 11, considering it works on virtually all compilers, including all previous versions of GCC. However I'll investigate further and report back.

**Comment by Saalvage** [comment] 2022-02-06 17:42
This is a minimal reproducible example: https://godbolt.org/z/re1Ez954x

So it appears that this is both a compiler and a doctest bug! On one hand The `operator<<` not being found is expected, due to some [weird lookup rules](https://stackoverflow.com/a/5195657/15262536) in combination with `operator<<` being declared for `doctest::String` inside of the `doctest` namespace. However, this should simply result in `has_insertion_operator` returning false, via SFINAE, instead, GCC fails to compile. To fix this and get the expected (but still semantically wrong) behavior we can replace `<<` with `operator<<` in the partial, true, specialization of `has_insertion_operator`.

How to fix this properly and in accordance with the standard I am not entirely sure. I am currently leaning towards declaring all `operator<<` overloads that `doctest` defines in the global namespace, however, I'm unsure if this is considered pollution and if it might have unintended side effects, so I'll have to reinvestigate this.

**Comment by Saalvage** [comment] 2022-02-14 01:41
I'm finally getting close to fixing this.
I just noticed that you might've just been looking for a fix for your code, in which case simply putting `operator<<` inside of namespace `N` OR making it a `friend` of `MyClass` would both fix it. 🙂

**Comment by Saalvage** [comment] 2022-04-28 01:10
In order to have this work doctest must be able to see the `operator<<` overload, which requires it being declared *before* including doctest, that's sadly just a C++ limitation. But other than that this has been fixed in dev!

**Closed by Saalvage** 2022-04-28 01:10 UTC
