### ISSUE TITLE
issue introduced in 2.4.7

### ISSUE THREAD

**Issue by onqtam** [doctest/doctest#630] opened 2022-04-08 14:09 UTC
How to reproduce:
https://godbolt.org/z/5Y87aMW8W

fails with gcc but no problem with clang - doctest version 2.4.7 introduced the problem and it's because of this commit:
https://github.com/doctest/doctest/commit/20dbad670e1a6ebf52d3aa12d55c7784070a115d

Seems to be related to this member and/or the lack of a move constructor for the `stringstream_proxy` class
https://github.com/adishavit/argh/blob/master/argh.h#L67

Logging this to not forget about it - I haven't dug any deeper though.

Original report: https://github.com/adishavit/argh/issues/72

**Comment by Tradias** [comment] 2022-04-13 09:38
Thank you for writing a reproducer, I was trying to write one as I am also facing this issue using doctest+Boost.Outcome. A fix would be welcome, currently stuck on doctest 2.4.6 because of it.

**Comment by Saalvage** [comment] 2022-04-16 02:39
@Tradias Could you please confirm that the PR solves this completely?

**Comment by Tradias** [comment] 2022-04-18 15:21
@Saalvage yes it solves it. Thank you for the fix!

**Comment by Saalvage** [comment] 2022-04-18 15:45
Fixed in dev!

**Closed by Saalvage** 2022-04-18 15:45 UTC
