### ISSUE TITLE
Add an "AND_GIVEN" macro for BDD-style test cases

### ISSUE THREAD

**Issue by TLS566ba** [doctest/doctest#840] opened 2024-01-18 13:35 UTC
## Description

Feature Request: Add a macro called `AND_GIVEN` that maps onto `SUBCASE` except that the subcase name is prefixed by "and given:".

This would be an alternative to `AND_WHEN`, but with a slightly different semantic meaning, improving the "executable specification" readability even further.

**Comment by cdeln** [comment] 2024-08-16 05:54
Duplicate of https://github.com/doctest/doctest/issues/43

**Closed** 2024-08-16 05:54 UTC
Labels: duplicate
