### ISSUE TITLE
docs: CMake build-system related -- Use FetchContent()

### ISSUE THREAD

**Issue by jenisys** [doctest/doctest#855] opened 2024-05-20 13:53 UTC
## Description

The `cmake` build-system support is described in [doc/markdown/build-systems.md](https://github.com/doctest/doctest/blob/master/doc/markdown/build-systems.md).

It is much simpler to use the `cmake FetchContent()` mechanism in another `cmake` project instead to use `ExternalProject` mechanism.

EXAMPLE:

```
# -- FILE: CMakeLists.txt
...
include(FetchContent)

FetchContent_Declare(doctest
    GIT_REPOSITORY https://github.com/doctest/doctest.git
    GIT_TAG        v2.4.11
)
FetchContent_MakeAvailable(doctest)
```

## Additional Point

The usage example for `cmake` can be improved, too:

```
add_executable(my_tests src_1.cpp src_2.cpp ...)
target_link_libraries(my_tests doctest)
```

BETTER (using `Modern CMake` like in other parts):

```
add_executable(my_tests)
target_sources(my_tests PRIVATE src_1.cpp src_2.cpp ...)
target_link_libraries(my_tests PRIVATE doctest::doctest)
```

### Extra information

* doctest version: **v2.4.11** (repository state)
* RELATED: Catch2 `cmake` description: [Catch2: docs/cmake-integration.md](https://github.com/catchorg/Catch2/blob/devel/docs/cmake-integration.md)

**Comment by cdeln** [comment] 2024-08-15 15:02
Duplicate of https://github.com/doctest/doctest/issues/698

**Closed by cdeln** 2024-08-15 15:02 UTC
Labels: duplicate
