### ISSUE TITLE
Vector contents show up as question mark

### ISSUE THREAD

**Issue by RPiAwesomeness** [doctest/doctest#248] opened 2019-06-24 18:25 UTC
## Description
I recently switched from the Catch2 library due to the improved compile times and everything seems to have gone flawlessly. However, I noticed that when comparing vector values fails, unlike Catch2 which will print the contents of the vectors, I just get this:

```
===============================================================================
test/test-encoding.cpp:73:
TEST CASE:  std::string to_utf16le_bytes(std::u16string)

test/test-encoding.cpp:79: FATAL ERROR: REQUIRE( result == expected ) is NOT correct!
  values: REQUIRE( {?} == {?} )

===============================================================================
```

whereas with Catch2 it provides the contents of the vectors:

```
test/test-encoding.cpp:90: FAILED:
  REQUIRE( result == expected )
with expansion:
  { '�', '2', '�', '2' }
  ==
  { '2', '�', '2', '�' }

===============================================================================
```

I know #170 matches this fairly exactly, but in that case he was dealing with templates and localization was the issue that was resolved, which I don't believe (off the top of my head) should apply in this situation. The contents of the vectors are `uint8_t` (`unsigned char` on most x64 systems), so I don't believe it has to do with the contents.

### Steps to reproduce

Compile the following with `doctest.h` (`g++ test.cpp doctest.h -o vector_test`) and see result:

```c++
// Tell doctest library to create a main for this file - only include this line once!
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

#include <vector>

#include "doctest.h"

using namespace std;

TEST_CASE("Compare vectors")
{
  vector<uint8_t> expected{ 0x32, 0xdb, 0x32, 0x8d };
  vector<uint8_t> result{ 0x32, 0x00, 0x32, 0x00 };

  REQUIRE(expected == result);
}
```

#### Result

```
[doctest] doctest version is "2.3.3"
[doctest] run with "--help" for options
===============================================================================
test/test-test.cpp:10:
TEST CASE:  Compare vectors

test/test-test.cpp:15: FATAL ERROR: REQUIRE( expected == result ) is NOT correct!
  values: REQUIRE( {?} == {?} )

===============================================================================
[doctest] test cases:      1 |      0 passed |      1 failed |      0 skipped
[doctest] assertions:      1 |      0 passed |      1 failed |
[doctest] Status: FAILURE!
```

* doctest version: **v2.3.3**
* Operating System: **Ubuntu 19.04 on Linux 5.0.0-17-generic**
* Compiler+version: **clang 8.0.0-3/g++ (Ubuntu 8.3.0-6ubuntu1) 8.3.0**

**Comment by onqtam** [comment] 2019-06-24 20:13
The lightness of doctest comes at a price - for example there is no out-of-the-box support for stringifications of containers. This is planned in the roadmap (could also come into a separate extensions header) - but even then it wouldn't be straightforward to decide on behalf of the user how many items of a container should be printed for example... Until then you could do whatever is done in the stringification example: https://github.com/onqtam/doctest/blob/master/examples/all_features/stringification.cpp

**Comment by RPiAwesomeness** [comment] 2019-06-25 13:11
Thanks for the quick response! With the stringification code, would I just copy and adjust this example to fit my needs?
```c++
namespace doctest
{
template <typename T>
struct StringMaker<std::list<T> >
{
    static String convert(const std::list<T>& in) {
        std::ostringstream oss;

        oss << "[";
        for(typename std::list<T>::const_iterator it = in.begin(); it != in.end(); ++it)
            oss << *it << ", ";
        oss << "]";

        return oss.str().c_str();
    }
};
}```

**Comment by onqtam** [comment] 2019-06-25 14:35
Yep - or you could bypass the ```StringMaker``` and use ```operator<<``` as shown in the docs as well :)

**Comment by dhardtke** [comment] 2019-09-08 00:31
I believe I have encountered a similar issue but am wondering why providing a custom `operator<<` implementation doesn't get picked up by doctest:
```cpp
template<class T>
std::ostream &operator<<(std::ostream &os, const std::list<T> &list) {
    unsigned long i = 0;
    for (auto el : list) {
        os << el;
        if (i < list.size() - 1) {
            os << ", ";
        }
        i++;
    }
    os << "\n";

    return os;
}
```

The above posted `StringMaker` approach on the other hand works well.

**Comment by onqtam** [comment] 2019-09-08 08:04
@dhardtke I think you might need to add it to the ```std``` namespace - like in the [example](https://github.com/onqtam/doctest/blob/master/examples/all_features/stringification.cpp#L15). This isn't allowed by the standard (adding anything in ```std``` except for specializations for templates such as ```hash```) but it practically works. I think its related to ADL.

**Comment by dhardtke** [comment] 2019-09-08 15:19
Ah right - totally forgot about that. It works now, thanks!

**Comment by cdeln** [comment] 2024-08-15 22:23
This is a duplicate of https://github.com/doctest/doctest/issues/192 .

Closing issue due to that and existing workaround.

**Closed** 2024-08-15 22:23 UTC
Labels: duplicate
