### ISSUE TITLE
"too many recursive substitutions of function template signatures" with NVCC 10.2.89

### ISSUE THREAD

**Issue by eyalroz** [doctest/doctest#522] opened 2021-07-08 11:22 UTC
I'm trying to convert the tests for [this repository](https://github.com/eyalroz/printf) from catch to doctest.  [This](https://github.com/eyalroz/printf/tree/switch-to-doctest) is the relevant branch, and the compilation of the host-side tests with NVCC 10.2.89 is failing.

From the first `CHECK()` line, which says:
```
  CHECK(test::printf("% d", 4232) == 5);
```
results in:
```
/home/eyalroz/src/mine/mpaland-printf/test/doctest.h(788): error #2824: too many recursive substitutions of function template signatures
          detected during:
            instantiation of "doctest::detail::declval" 
/home/eyalroz/src/mine/mpaland-printf/test/test_suite.cpp(112): here
            instantiation of "doctest::detail::declval" 
/home/eyalroz/src/mine/mpaland-printf/test/test_suite.cpp(112): here
            instantiation of "doctest::detail::declval" 
/home/eyalroz/src/mine/mpaland-printf/test/test_suite.cpp(112): here
            instantiation of "doctest::detail::declval" 
/home/eyalroz/src/mine/mpaland-printf/test/test_suite.cpp(112): here
            instantiation of "doctest::detail::declval" 
/home/eyalroz/src/mine/mpaland-printf/test/test_suite.cpp(112): here
            [ 92 instantiation contexts not shown ]
            instantiation of "doctest::detail::declval" 
/home/eyalroz/src/mine/mpaland-printf/test/test_suite.cpp(112): here
            instantiation of "doctest::detail::declval" 
/home/eyalroz/src/mine/mpaland-printf/test/test_suite.cpp(112): here
            instantiation of "doctest::detail::declval" 
/home/eyalroz/src/mine/mpaland-printf/test/test_suite.cpp(112): here
            instantiation of "doctest::detail::declval" 
/home/eyalroz/src/mine/mpaland-printf/test/test_suite.cpp(112): here
            instantiation of "doctest::detail::Expression_lhs<L>::operator== [with L=int]" 
/home/eyalroz/src/mine/mpaland-printf/test/test_suite.cpp(112): here
```

**Comment by cwpearson** [comment] 2022-03-03 04:20
I have this same problem, also with CUDA 10.2.89

https://github.com/sandialabs/tenzing-core/blob/31286db322b7006f32364bd52a6b7e38c4cfbb31/test/test_expand_spmv.cu#L44

Exactly the same output

**Comment by gsjaardema** [comment] 2022-05-19 21:35
I have the same issue with intel-19.0.X

**Comment by Saalvage** [comment] 2022-10-03 22:17
Likely related to the issues isaevil is having in #555.
Would someone (@eyalroz @cwpearson) be so kind as to test whether it's working correctly on the [fix-522 branch](https://github.com/doctest/doctest/tree/fix-522)?

**Comment by eyalroz** [comment] 2022-10-04 06:12
@Saalvage : Unfortunately, my tests are now more closely tied into catch2; and I deleted the branch; so I can't easily check this :-(

**Comment by Saalvage** [comment] 2022-10-06 18:11
@eyalroz No worries! Thank you for getting back to me.
Either way, I've decided to try and add CI for NVCC to 1. test the proposed fix and 2. prevent regression. However, I am struggling to get it running with CMake, since despite ´CMAKE_CXX_COMPILER` being set to `nvcc`, `CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang"` returns true, resulting in it attempting to apply various flags which nvcc does not support. Are you aware of any CMake properties which would allow us to branch on nvcc being used, similar to how `MSVC` allows branching on whether clang is actually being used as clang-cl?

Progress of the CI integration can be found on the [nvcc-ci branch](https://github.com/doctest/doctest/tree/nvcc-ci).

**Comment by Saalvage** [comment] 2022-12-17 00:47
This should be fixed in dev now! If any issues persist please reopen/open a new issue.

**Closed by Saalvage** 2022-12-17 00:47 UTC
