### ISSUE TITLE
Weird compilation error when using CHECK_THROWS/CHECK_THROWS_AS on Visual Studio 2019 with no exceptions

### ISSUE THREAD

**Issue by yeputons** [doctest/doctest#633] opened 2022-04-14 13:34 UTC
## Description
Consider the following example:
```c++
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
// #define _CPPUNWIND
#include "doctest.h"
TEST_CASE("") {
    DOCTEST_CHECK_THROWS_AS(throw 0, int);
//    DOCTEST_ASSERT_THROWS_AS(throw 0, DT_CHECK_THROWS_AS, "", int);
}
```

When compiled with `cl /std:c++17 a.cpp` it produces the following error:

```
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30142.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

a.cpp
a.cpp(5): error C2062: type 'int' unexpected
```

[The culprit here](https://stackoverflow.com/a/71872153/767632) is that Visual Studio command line compiler disables C++ exceptions by default. It is [correctly detected by doctest](https://github.com/doctest/doctest/blob/7b9885133108ae301ddd16e2651320f54cafeba7/doctest/doctest.h#L277-L279) (`_CPPUNWIND` is [a VS-specific macro](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-160)), hence `DOCTEST_CONFIG_NO_EXCEPTIONS` is automatically defined and then [some internal macros are `undef`ed](https://github.com/doctest/doctest/blob/7b9885133108ae301ddd16e2651320f54cafeba7/doctest/doctest.h#L2391).

For example, if I define `_CPPUNWIND` myself, the code compiles, kinda works and I get away with a warning:

```
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30142.1 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

a.cpp
a.cpp(5): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
Microsoft (R) Incremental Linker Version 14.29.30142.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:a.exe
a.obj
```

The same behavior happens if I do not play with `_CPPUNWIND`, but use `DOCTEST_ASSERT_THROWS_AS` directly intead of `DOCTEST_CHECK_THROWS_AS`: no compilation error, "just" a warning.

It makes some sense to disable exceptions and err if they are not supported by the compiler, but the error message is misleading for whatever reason: VS does not err about `DOCTEST_CHECK_THROWS_AS` being undefined and complains about something else instead.

I'm not exactly sure how to handle this situation. Maybe replace exception-handlind macros with a call to an undefined function like `doctest_config_no_exceptions_is_enabled_Exception_catching_assertions_will_not_work()`? Or simply `#define DOCTEST_CHECK_THROWS_AS(...) DOCTEST_CHECK_THROWS_AS()` for Visual Studio (maybe other compiles as well) to avoid weird syntax error, it will err like this:

```
a.cpp(5): error C3861: 'DOCTEST_CHECK_THROWS_AS': identifier not found
```

I like the latter more because it yields a compilation error, not linkage error.

### Steps to reproduce
1. Install Visual Studio 2019 with C++ compiler. Community version should be ok, other versions should be ok as well.
2. Open the "Developer Command Prompt for VS 2019"
3. Navigate to a directory with `a.cpp` from above and `doctest.h`
4. Run `cl /std:c++17 a.cpp`
5. Observe the compilation error

### Extra information
* doctest version: **v2.4.6*
* Operating System: **Windows 10 Pro 21H1**
* Compiler+version: **Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30142.1 for x64** (Visual Studio 2019 Community 16.11.12)

**Comment by yeputons** [comment] 2022-04-14 13:50
Wild guess from @LDVSOFT: Visual C++ may be considering `undefined_macro(a, b)` a function call, which it is in C as you don't _have to_ declare a function before calling it. Hence, it's impossible to know that `undefined_macro` is really undefined and it goes on to parse arguments. However, a type cannot be a function's argument.

**Comment by Saalvage** [comment] 2022-04-28 02:59
This appears to be a duplicate of #439?

**Comment by Saalvage** [comment] 2022-04-30 16:22
Assuming (implemented) duplicate, if not, please reopen!

**Closed by Saalvage** 2022-04-30 16:22 UTC
