### ISSUE TITLE
v2.4.9 do not support CHECK_EQ for 2 ptr

### ISSUE THREAD

**Issue by hurricane1026** [doctest/doctest#686] opened 2022-08-17 09:48 UTC
## Description
in some cases, I need to compare 2 ptrs have same memory address or not.
In doctest v2.4.7, just use 
`CHECK_EQ(ptr1, &(obj2);`
it just works well.
but in v2.4.9, it cannot be compiled with messsage "
```
error: cannot initialize a parameter of type 'const void *' with an lvalue of type 'void *(*)(unsigned long)'
            filldata<const void*>::fill(stream, in);
                                                ^~

```
and I need change the Assertion statement to 
`CHECK_EQ(ptr1 == &obj2, true);`

### Steps to reproduce
use v2.4.8 with assertion of CHECK_EQ 2 ptrs.

### Extra information
the new macro DOCTEST_STRINGIFY maybe t the rootcause.

* doctest version: **v2.4.9**
* Operating System: **Fedora LInux 36 with 5.18.17-200 kernel**
* Compiler+version: **clang++ 14.0.0-1.fc36 will c++20 flag **

**Comment by nickdademo** [comment] 2022-08-22 05:59
Related to or duplicate of? https://github.com/doctest/doctest/issues/665

**Comment by hurricane1026** [comment] 2022-08-23 03:55
> Related to or duplicate of? #665

I think so.

**Comment by Saalvage** [comment] 2022-10-04 00:35
Fixed in dev!

**Closed by Saalvage** 2022-10-04 00:35 UTC

**Comment by serge-sans-paille** [comment] 2022-12-03 18:54
@Saalvage would that make sense to do a 2.4.10 release, so that we can have that patch included?

**Comment by dankamongmen** [comment] 2022-12-03 19:05
> @Saalvage would that make sense to do a 2.4.10 release, so that we can have that patch included?

i'd really appreciate this -- multiple distros have pulled n 2.4.9, and notcurses (and other) builds are broken everywhere that's been done.
