### ISSUE TITLE
build failure with gcc-11.2 when using user declared operator<<(ostream, vector)

### ISSUE THREAD

**Issue by nlitsme** [doctest/doctest#551] opened 2021-11-16 00:12 UTC
## Description

When using a user declared ```operator<<(std::ostream, const std::vector<int>& v)```,
and compiling with the latest gcc version ( 11.2.0 ), I get this compiler error:

    /usr/include/doctest/doctest.h:835:39: error: no match for ‘operator<<’ (operand types are ‘std::ostream’
        {aka ‘std::basic_ostream<char, std::char_traits<char> >’} and ‘const std::vector<int>’)

### Steps to reproduce

With this `errordemo.cpp` file:
```
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

std::ostream& operator<<(std::ostream& os, const std::vector<int>& v)
{
	return os << "intvector";
}

TEST_CASE("test") {
	std::vector<int> v;
	CHECK( v == v );
}
```

and compile with:
```
g++-11  errordemo.cpp
```
And you will get lots of compiler errors, the full log is here: [x-errors.txt](https://github.com/onqtam/doctest/files/7542355/x-errors.txt).

### Extra information
 - On the other hand, compiling the same with any of these compilers works just fine:
   * g++-10
   * clang++-11
   * clang++-12
   * clang++-13
   * msvc 19.29

 - When commenting out the `operator<<` function the problem disappears.
 - When using `catch` instead of `doctest`, this works even with g++ 11.2.

Only the combination `doctest`, `g++ 11.2` and the user defined `operator` will produce the error.
Note that this also fails when using other templated types, like std::array, std::tuple, or std::optional.

I am not sure if this is a problem with gcc, or with doctest.

* doctest version: **v2.4.6**
* Operating System: **Debian testing**, **linux 5.14.0-4-amd64**
* Compiler+version: **GCC 11.2.0** for amd64

**Comment by zeux** [comment] 2021-11-20 16:46
FWIW we had a similar issue and solved it by moving the operator to the `std` namespace.

**Comment by nlitsme** [comment] 2021-11-20 19:48
I can confirm that adding `namespace std { ... }`   around the `operator<<`.  does solve the problem. 
But I dont understand why this has become a problem with the g++-11 version of the compiler.

**Comment by mikucionisaau** [comment] 2021-11-20 20:40
Could it be due to [ADL](https://en.cppreference.com/w/cpp/language/adl) rules? (which is a very frustrating topic, btw)

Perhaps g++-11 implements ADL differently, given that it ships partial implementation of modules.
Also clang++-13 does not have this issue.

**Comment by nlitsme** [comment] 2021-11-21 08:42
I found this SO thread: https://stackoverflow.com/questions/2479253/which-namespace-does-operator-stream-go-to

Here is the relevant standard entry: http://eel.is/c++draft/basic.lookup.argdep#def:lookup,argument-dependent

And here an explanation on cppreference.com: https://en.cppreference.com/w/cpp/language/adl

**Comment by mikucionisaau** [comment] 2021-11-23 11:17
Summary of the [SO](https://stackoverflow.com/questions/2479253/which-namespace-does-operator-stream-go-to) answers:
1. Herb Sutter (one of C++ Standard gurus) says that non-member functions should be part of its argument namespace (see also [his book](http://micro-os-plus.github.io/develop/sutter-101/#57-keep-a-type-and-its-nonmember-function-interface-in-the-same-namespace), [Core Guidelines: C.5](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-helper) and [Core Guidelines: C.168](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Ro-namespace)). So this solutions works, but!
2. Others object extending `std` namespace saying that the standard forbids that. I found the following in the [C++ Standard draft](https://eel.is/c++draft/namespace.std):

> Unless otherwise specified, the behavior of a C++ program is undefined if it adds declarations or definitions to namespace std or to a namespace within namespace std.

Also:

> A program may explicitly instantiate a class template defined in the standard library only if the declaration (a) depends on the name of at least one program-defined type and (b) the instantiation meets the standard library requirements for the original template.

And:

> Other than in namespace std or in a namespace within namespace std, a program may provide an overload for any library function template designated as a customization point, provided that (a) the overload's declaration depends on at least one user-defined type and (b) the overload meets the standard library requirements for the customization point.164
> [Note 2: This permits a (qualified or unqualified) call to the customization point to invoke the most appropriate overload for the given arguments. — end note]

So I believe we have a "permission" to define our own output operator even in the `std` namespace, but it feels dirty (the problem will resurface if multiple definitions are given). It does not answer why `g++-11` errs.

3. A compromise solution is to define such non-member function in a separate namespace, which imports the `std` with `using namespace std;`. So this does not seem to break any rules, the polution is limited to that namespace and interestingly, it also works! So that's another question why `g++-11` does not err here but errs on global scope.

Anyway, the immediately affected doctest code is performing SFINAE when checking if `operator<<(std::ostream&, const vector<int>&)` is available, and SFINAE is supposed to fail silently if the operator is not available. If the `operator<<` is not supplied, then g++-11/doctest simply outputs `{?}` -- works as expected. But in this case, the operator is present and compiler fails with an error -- a contradiction. 
Maybe the issue is at a larger context. I looked at the preprocessed code and I still cannot see anything wrong. My conclusion is that something is wrong with `g++-11`.

**Comment by Saalvage** [comment] 2022-02-14 03:11
Confirmed SFINAE failure as a bug in GCC11. [link](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104425)

#615 adds a workaround. In order for the `operator<<` to actually be used, you should declare it before including `doctest.h` though!

**Comment by Saalvage** [comment] 2022-04-28 01:12
All merged into dev!

**Closed by Saalvage** 2022-04-28 01:12 UTC
Labels: bug
