### ISSUE TITLE
[Feature] constant expression checking

### ISSUE THREAD

**Issue by cjdb** [doctest/doctest#319] opened 2019-12-16 11:32 UTC
## Description
It would be wonderful if doctest supported checking compile-time expressions and run-time expressions _together_. I'd like to check that my `constexpr` functions indeed work as compile-time, and at run-time.

### Example

```cpp
template<typename T>
constexpr T square(T const& t) noexcept
{
   if (std::is_constant_evaluated()) {
      return t * t * t; // contrived, but hopefully communicates what's missing
   }
   return t * t;
}

// current
TEST_CASE("only happens at run-time AFAIU") {
   CHECK(square(0) == 0);
   CHECK(square(1.0) == 1.0);
   CHECK(square(2) == 4); // error not caught
}

// proposed
CONSTEXPR_TEST_CASE("happens at both compile-time and run-time") {
   CHECK(square(0) == 0);
   CHECK(square(1.0) == 1.0);
   CHECK(square(2) == 4); // error in the constexpr case
}
```

### Extra information
I doubt this is possible in C++17, but it is certainly doable from C++20 onward (even if it's a bit clunky for now). `static_assert` is also not helpful here, since only guaranteed constant expressions are allowed to be checked using a `static_assert`.

**Comment by onqtam** [comment] 2019-12-16 17:59
So what you basically want is to try to evaluate at compile time, and if not possible - at runtime?
How would that be done in C++20? Perhaps with the use of ```std::is_constant_evaluated()```... I'm certainly open to suggestions, but I assume this is a niche use case.

**Comment by cjdb** [comment] 2019-12-16 19:12
> So what you basically want is to try to evaluate at compile time, and if not possible - at runtime?

Not quite. I want it to be evaluated at both compile-time _and_ at run-time in all cases. The former is not only to check that the result comes out correctly at compile-time, but also to prove that that the functionality can be constant evaluated.

**Comment by onqtam** [comment] 2019-12-16 21:18
I doubt such a thing would go into the main doctest header, but I've been thinking of making an extensions header for quite a while - perhaps that could be a place for such a thing. I'd certainly consider it if someone provides an implementation :)

**Comment by cdeln** [comment] 2024-08-16 05:14
Duplicate of https://github.com/doctest/doctest/issues/250 .

It's quite easy to implement yourself though. I tested one of my constexpr friendly libs like this: https://github.com/cdeln/cpp_enum_set/blob/master/test/include/testing.hpp

Still a good feature I think, not so much because you want to check that the results are the same (no sane person would use different code paths and runtime and compile time IMO), but if the results do produce different results that is most likely a compiler bug (see this issue I found in GCC for example: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116331 )

Closing due to above reasons.

**Closed** 2024-08-16 05:14 UTC
Labels: duplicate
